MovieSelling2/Controllers/ScheduleController.cs
using MovieSelling.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieSelling.Controllers
{
    public class ScheduleController : Controller
    {
        //
        // GET: /Schedule/

        public ActionResult Index()
        {
            
            Dictionary<string, Dictionary<int, List<string>>> model = getFromDatabase();
            return View(model);
        }

        private Dictionary<string, Dictionary<int, List<string>>> getFromDatabase()
        {
            Dictionary<string, Dictionary<int, List<string>>> model = new Dictionary<string, Dictionary<int, List<string>>>();
            DateTime now = DateTime.UtcNow.AddHours(7);
            for (int i = 0; i < 4; i++)
            {
                model.Add(now.ToString(DatabaseHelper.DateFormat), getScheduleByDate(now.ToString(DatabaseHelper.DateFormat)) );
                now = now.AddDays(1);
            }
            return model;
        }


        private Dictionary<int,List<string>> getScheduleByDate(string dateSche)
        {
            Dictionary<int, List<string>> myDic = new Dictionary<int, List<string>>();
            // 
            using (SqlConnection conn = new SqlConnection(System.Web.Configuration.WebConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            {
                conn.Open();
                string sqlSelect = @"select * from Schedule where [DateSche]=@date";
                using (SqlCommand cmd = new SqlCommand(sqlSelect, conn))
                {
                    cmd.Parameters.AddWithValue("@date", dateSche);
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        string startTime = reader[DatabaseHelper.StartTime].ToString();
                        int filmID = (int) reader[DatabaseHelper.FilmID];

                        if (myDic.ContainsKey(filmID))
                            myDic[filmID].Add(startTime);
                        else
                            myDic.Add(filmID, new List<string>() { startTime});
                    }
                }
            }

            foreach (var item in myDic)
            {
                item.Value.Sort();                        
            }
            return myDic;
        }
    }
}

MovieSelling2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/myquery")
</head>


<body>
    <!-- Shell -->
    <div id="shell">
        <!-- Header -->
        <div id="header">
            <h1 id="logo"><a href="#">BnP</a></h1>
            <div class="social">
                <span></span>
                <ul></ul>
            </div>
            <div id="banner">
            </div>
            <div id="banner-right">
            </div>
            <!-- Navigation -->
            <div id="navigation">
                <ul>
                    <li><a class="@MovieSelling.DatabaseHelper.Home" href=@Url.Action("index", "film")>TRANG CHỦ</a></li>
                    <li><a class="@MovieSelling.DatabaseHelper.New" href=@Url.Action("News", "Home")>TIN TỨC</a></li>
                    <li><a class="@MovieSelling.DatabaseHelper.Schedule" href=@Url.Action("index", "Schedule")>LỊCH CHIẾU</a></li>
                    <li><a class="@MovieSelling.DatabaseHelper.Booking" href=@Url.Action("step1", "booking", new { FilmID = 0, dateSche = "", timeSChe = "" })>ĐẶT VÉ</a></li>
                    <li><a class="@MovieSelling.DatabaseHelper.Ticket" href=@Url.Action("Ticket", "Home")>GIÁ VÉ</a></li>
                    <li><a class="@MovieSelling.DatabaseHelper.Contact" href=@Url.Action("Contact", "Home")>LIÊN HỆ</a></li>
                </ul>
            </div>
            <!-- end Navigation -->
        </div>
        <!-- end Header -->
        @RenderBody()


    </div>
    <!-- end Shell -->
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>